spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/CricketAuctionDb?createDatabaseIfNotExist=true
        username: root
        password: CSr1407@
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8085